name: "Init Chaos Cloud Simulation"
description: "Kick off simulations on cloud"
author: "[Chaos Labs]"

branding:
  icon: 'message-square'
  color: 'purple'

inputs:
  chaos_token:
    description: "Chaos token"
    required: true
  github:
    description: "github meta data"
    required: true

runs:
  using: "node12"
  main: "index.js"
