name: Chaos Simulations

# Triggers the workflow on push or pull request events
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          CHAOS_TOKEN: ${{secrets.CHAOS_TOKEN}}
          CHAOS_ENDPOINT: ${{secrets.CHAOS_ENDPOINT}}
          CHAOS_ID: ${{secrets.CHAOS_ID}}
